-- Add comprehensive list of NSE and BSE stocks (fixed duplicates)
INSERT INTO public.stocks (symbol, name, exchange, sector) VALUES
-- NSE Stocks
('RELIANCE', 'Reliance Industries Ltd', 'NSE', 'Energy'),
('TCS', 'Tata Consultancy Services Ltd', 'NSE', 'IT'),
('HDFCBANK', 'HDFC Bank Ltd', 'NSE', 'Banking'),
('INFY', 'Infosys Ltd', 'NSE', 'IT'),
('ICICIBANK', 'ICICI Bank Ltd', 'NSE', 'Banking'),
('HINDUNILVR', 'Hindustan Unilever Ltd', 'NSE', 'FMCG'),
('ITC', 'ITC Ltd', 'NSE', 'FMCG'),
('SBIN', 'State Bank of India', 'NSE', 'Banking'),
('BHARTIARTL', 'Bharti Airtel Ltd', 'NSE', 'Telecom'),
('KOTAKBANK', 'Kotak Mahindra Bank Ltd', 'NSE', 'Banking'),
('LT', 'Larsen & Toubro Ltd', 'NSE', 'Infrastructure'),
('HCLTECH', 'HCL Technologies Ltd', 'NSE', 'IT'),
('AXISBANK', 'Axis Bank Ltd', 'NSE', 'Banking'),
('ASIANPAINT', 'Asian Paints Ltd', 'NSE', 'Consumer Goods'),
('MARUTI', 'Maruti Suzuki India Ltd', 'NSE', 'Automobile'),
('SUNPHARMA', 'Sun Pharmaceutical Industries Ltd', 'NSE', 'Pharma'),
('TITAN', 'Titan Company Ltd', 'NSE', 'Consumer Goods'),
('WIPRO', 'Wipro Ltd', 'NSE', 'IT'),
('ULTRACEMCO', 'UltraTech Cement Ltd', 'NSE', 'Cement'),
('NESTLEIND', 'Nestle India Ltd', 'NSE', 'FMCG'),
('ONGC', 'Oil & Natural Gas Corporation Ltd', 'NSE', 'Energy'),
('TATAMOTORS', 'Tata Motors Ltd', 'NSE', 'Automobile'),
('NTPC', 'NTPC Ltd', 'NSE', 'Power'),
('BAJFINANCE', 'Bajaj Finance Ltd', 'NSE', 'Finance'),
('TECHM', 'Tech Mahindra Ltd', 'NSE', 'IT'),
('M&M', 'Mahindra & Mahindra Ltd', 'NSE', 'Automobile'),
('POWERGRID', 'Power Grid Corporation of India Ltd', 'NSE', 'Power'),
('TATASTEEL', 'Tata Steel Ltd', 'NSE', 'Metals'),
('ADANIENT', 'Adani Enterprises Ltd', 'NSE', 'Diversified'),
('BAJAJFINSV', 'Bajaj Finserv Ltd', 'NSE', 'Finance'),
('COALINDIA', 'Coal India Ltd', 'NSE', 'Mining'),
('DIVISLAB', 'Divi''s Laboratories Ltd', 'NSE', 'Pharma'),
('EICHERMOT', 'Eicher Motors Ltd', 'NSE', 'Automobile'),
('DRREDDY', 'Dr. Reddy''s Laboratories Ltd', 'NSE', 'Pharma'),
('INDUSINDBK', 'IndusInd Bank Ltd', 'NSE', 'Banking'),
('JSWSTEEL', 'JSW Steel Ltd', 'NSE', 'Metals'),
('CIPLA', 'Cipla Ltd', 'NSE', 'Pharma'),
('BRITANNIA', 'Britannia Industries Ltd', 'NSE', 'FMCG'),
('GRASIM', 'Grasim Industries Ltd', 'NSE', 'Diversified'),
('HINDALCO', 'Hindalco Industries Ltd', 'NSE', 'Metals'),
('TATACONSUM', 'Tata Consumer Products Ltd', 'NSE', 'FMCG'),
('HEROMOTOCO', 'Hero MotoCorp Ltd', 'NSE', 'Automobile'),
('APOLLOHOSP', 'Apollo Hospitals Enterprise Ltd', 'NSE', 'Healthcare'),
('SHREECEM', 'Shree Cement Ltd', 'NSE', 'Cement'),
('ADANIPORTS', 'Adani Ports and Special Economic Zone Ltd', 'NSE', 'Infrastructure'),
('BPCL', 'Bharat Petroleum Corporation Ltd', 'NSE', 'Energy'),
('SBILIFE', 'SBI Life Insurance Company Ltd', 'NSE', 'Insurance'),
('HDFCLIFE', 'HDFC Life Insurance Company Ltd', 'NSE', 'Insurance'),
('VEDL', 'Vedanta Ltd', 'NSE', 'Metals'),
('IOC', 'Indian Oil Corporation Ltd', 'NSE', 'Energy'),
('DABUR', 'Dabur India Ltd', 'NSE', 'FMCG'),
('GODREJCP', 'Godrej Consumer Products Ltd', 'NSE', 'FMCG'),
('MARICO', 'Marico Ltd', 'NSE', 'FMCG'),
('PIDILITIND', 'Pidilite Industries Ltd', 'NSE', 'Chemicals'),
('TATAPOWER', 'Tata Power Company Ltd', 'NSE', 'Power'),
('DLF', 'DLF Ltd', 'NSE', 'Real Estate'),
('BANKBARODA', 'Bank of Baroda', 'NSE', 'Banking'),
('PNB', 'Punjab National Bank', 'NSE', 'Banking'),
('CANBK', 'Canara Bank', 'NSE', 'Banking'),
('UNIONBANK', 'Union Bank of India', 'NSE', 'Banking'),
('INDHOTEL', 'The Indian Hotels Company Ltd', 'NSE', 'Hospitality'),
('BOSCHLTD', 'Bosch Ltd', 'NSE', 'Automobile'),
('HAVELLS', 'Havells India Ltd', 'NSE', 'Consumer Goods'),
('MOTHERSON', 'Samvardhana Motherson International Ltd', 'NSE', 'Automobile'),
('AMBUJACEM', 'Ambuja Cements Ltd', 'NSE', 'Cement'),
('ACC', 'ACC Ltd', 'NSE', 'Cement'),
('MCDOWELL-N', 'United Spirits Ltd', 'NSE', 'FMCG'),
('SIEMENS', 'Siemens Ltd', 'NSE', 'Infrastructure'),
('TVSMOTOR', 'TVS Motor Company Ltd', 'NSE', 'Automobile'),
('BAJAJ-AUTO', 'Bajaj Auto Ltd', 'NSE', 'Automobile'),
('MRF', 'MRF Ltd', 'NSE', 'Automobile'),
('ESCORTS', 'Escorts Kubota Ltd', 'NSE', 'Automobile'),
('ZYDUSLIFE', 'Zydus Lifesciences Ltd', 'NSE', 'Pharma'),
('LUPIN', 'Lupin Ltd', 'NSE', 'Pharma'),
('BIOCON', 'Biocon Ltd', 'NSE', 'Pharma'),
('TORNTPHARM', 'Torrent Pharmaceuticals Ltd', 'NSE', 'Pharma'),
('ALKEM', 'Alkem Laboratories Ltd', 'NSE', 'Pharma'),
('AUROPHARMA', 'Aurobindo Pharma Ltd', 'NSE', 'Pharma'),
('GLENMARK', 'Glenmark Pharmaceuticals Ltd', 'NSE', 'Pharma'),
('CONCOR', 'Container Corporation of India Ltd', 'NSE', 'Logistics'),
('ADANIGREEN', 'Adani Green Energy Ltd', 'NSE', 'Power'),
('ADANITRANS', 'Adani Transmission Ltd', 'NSE', 'Power'),
('PAGEIND', 'Page Industries Ltd', 'NSE', 'Consumer Goods'),
('BERGEPAINT', 'Berger Paints India Ltd', 'NSE', 'Consumer Goods'),
('VOLTAS', 'Voltas Ltd', 'NSE', 'Consumer Goods'),
('WHIRLPOOL', 'Whirlpool of India Ltd', 'NSE', 'Consumer Goods'),
('COLPAL', 'Colgate-Palmolive (India) Ltd', 'NSE', 'FMCG'),
('MUTHOOTFIN', 'Muthoot Finance Ltd', 'NSE', 'Finance'),
('CHOLAFIN', 'Cholamandalam Investment and Finance Company Ltd', 'NSE', 'Finance'),
('LICHSGFIN', 'LIC Housing Finance Ltd', 'NSE', 'Finance'),
('RECLTD', 'REC Ltd', 'NSE', 'Finance'),
('PFC', 'Power Finance Corporation Ltd', 'NSE', 'Finance'),
('IRCTC', 'Indian Railway Catering and Tourism Corporation Ltd', 'NSE', 'Services'),
('IRFC', 'Indian Railway Finance Corporation Ltd', 'NSE', 'Finance'),
('SAIL', 'Steel Authority of India Ltd', 'NSE', 'Metals'),
('NMDC', 'NMDC Ltd', 'NSE', 'Mining'),
('ZEEL', 'Zee Entertainment Enterprises Ltd', 'NSE', 'Media'),
('PVRINOX', 'PVR INOX Ltd', 'NSE', 'Media'),
('BATAINDIA', 'Bata India Ltd', 'NSE', 'Consumer Goods'),
('TRENT', 'Trent Ltd', 'NSE', 'Retail'),
('DMART', 'Avenue Supermarts Ltd', 'NSE', 'Retail'),
('JUBLFOOD', 'Jubilant FoodWorks Ltd', 'NSE', 'Food Services'),
('BHARATFORG', 'Bharat Forge Ltd', 'NSE', 'Automobile'),
('CUMMINSIND', 'Cummins India Ltd', 'NSE', 'Automobile'),
('ASHOKLEY', 'Ashok Leyland Ltd', 'NSE', 'Automobile'),
('CROMPTON', 'Crompton Greaves Consumer Electricals Ltd', 'NSE', 'Consumer Goods'),
('DIXON', 'Dixon Technologies (India) Ltd', 'NSE', 'Electronics'),
('INDUSTOWER', 'Indus Towers Ltd', 'NSE', 'Telecom'),
('POLYCAB', 'Polycab India Ltd', 'NSE', 'Infrastructure'),
('TORNTPOWER', 'Torrent Power Ltd', 'NSE', 'Power'),
('JINDALSTEL', 'Jindal Steel & Power Ltd', 'NSE', 'Metals'),
('HINDZINC', 'Hindustan Zinc Ltd', 'NSE', 'Metals'),
('NATIONALUM', 'National Aluminium Company Ltd', 'NSE', 'Metals'),
('BALKRISIND', 'Balkrishna Industries Ltd', 'NSE', 'Automobile'),
('APOLLOTYRE', 'Apollo Tyres Ltd', 'NSE', 'Automobile'),
('CEAT', 'CEAT Ltd', 'NSE', 'Automobile'),
('GMRINFRA', 'GMR Infrastructure Ltd', 'NSE', 'Infrastructure'),
('L&TFH', 'L&T Finance Holdings Ltd', 'NSE', 'Finance'),
('ICICIPRULI', 'ICICI Prudential Life Insurance Company Ltd', 'NSE', 'Insurance'),
('SBICARD', 'SBI Cards and Payment Services Ltd', 'NSE', 'Finance'),
('PIIND', 'PI Industries Ltd', 'NSE', 'Chemicals'),
('SRF', 'SRF Ltd', 'NSE', 'Chemicals'),
('AARTI', 'Aarti Industries Ltd', 'NSE', 'Chemicals'),
('DEEPAKNI', 'Deepak Nitrite Ltd', 'NSE', 'Chemicals'),
('GNFC', 'Gujarat Narmada Valley Fertilizers & Chemicals Ltd', 'NSE', 'Chemicals'),
('CHAMBLFERT', 'Chambal Fertilisers and Chemicals Ltd', 'NSE', 'Chemicals'),
('COROMANDEL', 'Coromandel International Ltd', 'NSE', 'Chemicals'),
('UPL', 'UPL Ltd', 'NSE', 'Chemicals'),
('PERSISTENT', 'Persistent Systems Ltd', 'NSE', 'IT'),
('COFORGE', 'Coforge Ltd', 'NSE', 'IT'),
('LTTS', 'L&T Technology Services Ltd', 'NSE', 'IT'),
('LTIM', 'LTIMindtree Ltd', 'NSE', 'IT'),
('MPHASIS', 'Mphasis Ltd', 'NSE', 'IT'),
('OFSS', 'Oracle Financial Services Software Ltd', 'NSE', 'IT'),
('TATAELXSI', 'Tata Elxsi Ltd', 'NSE', 'IT'),
('SONATSOFTW', 'Sonata Software Ltd', 'NSE', 'IT'),
('RAMCOCEM', 'The Ramco Cements Ltd', 'NSE', 'Cement'),
('JKCEMENT', 'JK Cement Ltd', 'NSE', 'Cement'),
('INDIACEM', 'India Cements Ltd', 'NSE', 'Cement'),
('PRESTIGE', 'Prestige Estates Projects Ltd', 'NSE', 'Real Estate'),
('GODREJPROP', 'Godrej Properties Ltd', 'NSE', 'Real Estate'),
('OBEROIRLTY', 'Oberoi Realty Ltd', 'NSE', 'Real Estate'),
('BRIGADE', 'Brigade Enterprises Ltd', 'NSE', 'Real Estate'),
('PHOENIXLTD', 'The Phoenix Mills Ltd', 'NSE', 'Real Estate'),
('IPCALAB', 'IPCA Laboratories Ltd', 'NSE', 'Pharma'),
('SYNGENE', 'Syngene International Ltd', 'NSE', 'Pharma'),
('LALPATHLAB', 'Dr. Lal PathLabs Ltd', 'NSE', 'Healthcare'),
('METROPOLIS', 'Metropolis Healthcare Ltd', 'NSE', 'Healthcare'),
('MAXHEALTH', 'Max Healthcare Institute Ltd', 'NSE', 'Healthcare'),
('FORTIS', 'Fortis Healthcare Ltd', 'NSE', 'Healthcare'),
('NAUKRI', 'Info Edge (India) Ltd', 'NSE', 'Services'),
('ZOMATO', 'Zomato Ltd', 'NSE', 'Food Services'),
('PAYTM', 'One 97 Communications Ltd', 'NSE', 'Fintech'),
('POLICYBZR', 'PB Fintech Ltd', 'NSE', 'Fintech'),
('DELHIVERY', 'Delhivery Ltd', 'NSE', 'Logistics'),
('ROUTE', 'Route Mobile Ltd', 'NSE', 'IT'),
('FSL', 'Firstsource Solutions Ltd', 'NSE', 'IT'),
-- BSE Listed Stocks (with corrected codes)
('500325', 'Reliance Industries Ltd', 'BSE', 'Energy'),
('532540', 'Tata Consultancy Services Ltd', 'BSE', 'IT'),
('500180', 'HDFC Bank Ltd', 'BSE', 'Banking'),
('500209', 'Infosys Ltd', 'BSE', 'IT'),
('532174', 'ICICI Bank Ltd', 'BSE', 'Banking'),
('500696', 'Hindustan Unilever Ltd', 'BSE', 'FMCG'),
('500875', 'ITC Ltd', 'BSE', 'FMCG'),
('500112', 'State Bank of India', 'BSE', 'Banking'),
('532454', 'Bharti Airtel Ltd', 'BSE', 'Telecom'),
('500247', 'Kotak Mahindra Bank Ltd', 'BSE', 'Banking'),
('500510', 'Larsen & Toubro Ltd', 'BSE', 'Infrastructure'),
('532281', 'HCL Technologies Ltd', 'BSE', 'IT'),
('532215', 'Axis Bank Ltd', 'BSE', 'Banking'),
('500820', 'Asian Paints Ltd', 'BSE', 'Consumer Goods'),
('532500', 'Maruti Suzuki India Ltd', 'BSE', 'Automobile'),
('524715', 'Sun Pharmaceutical Industries Ltd', 'BSE', 'Pharma'),
('500114', 'Titan Company Ltd', 'BSE', 'Consumer Goods'),
('507685', 'Wipro Ltd', 'BSE', 'IT'),
('532538', 'UltraTech Cement Ltd', 'BSE', 'Cement'),
('500790', 'Nestle India Ltd', 'BSE', 'FMCG'),
('500312', 'Oil & Natural Gas Corporation Ltd', 'BSE', 'Energy'),
('500570', 'Tata Motors Ltd', 'BSE', 'Automobile'),
('532555', 'NTPC Ltd', 'BSE', 'Power'),
('500034', 'Bajaj Finance Ltd', 'BSE', 'Finance'),
('532755', 'Tech Mahindra Ltd', 'BSE', 'IT'),
('500520', 'Mahindra & Mahindra Ltd', 'BSE', 'Automobile'),
('532898', 'Power Grid Corporation of India Ltd', 'BSE', 'Power'),
('500470', 'Tata Steel Ltd', 'BSE', 'Metals'),
('512599', 'Adani Enterprises Ltd', 'BSE', 'Diversified'),
('532978', 'Bajaj Finserv Ltd', 'BSE', 'Finance'),
('533278', 'Coal India Ltd', 'BSE', 'Mining'),
('532488', 'Divi''s Laboratories Ltd', 'BSE', 'Pharma'),
('505200', 'Eicher Motors Ltd', 'BSE', 'Automobile'),
('500124', 'Dr. Reddy''s Laboratories Ltd', 'BSE', 'Pharma'),
('532187', 'IndusInd Bank Ltd', 'BSE', 'Banking'),
('500228', 'JSW Steel Ltd', 'BSE', 'Metals'),
('500087', 'Cipla Ltd', 'BSE', 'Pharma'),
('500825', 'Britannia Industries Ltd', 'BSE', 'FMCG'),
('500300', 'Grasim Industries Ltd', 'BSE', 'Diversified'),
('500440', 'Hindalco Industries Ltd', 'BSE', 'Metals'),
('500800', 'Tata Consumer Products Ltd', 'BSE', 'FMCG'),
('500182', 'Hero MotoCorp Ltd', 'BSE', 'Automobile'),
('526299', 'Apollo Hospitals Enterprise Ltd', 'BSE', 'Healthcare'),
('500387', 'Shree Cement Ltd', 'BSE', 'Cement'),
('532921', 'Adani Ports and Special Economic Zone Ltd', 'BSE', 'Infrastructure'),
('500547', 'Bharat Petroleum Corporation Ltd', 'BSE', 'Energy'),
('542066', 'SBI Life Insurance Company Ltd', 'BSE', 'Insurance'),
('540777', 'HDFC Life Insurance Company Ltd', 'BSE', 'Insurance');